### ISSUE TITLE
question: how to benchmark async function?

### ISSUE THREAD

**Issue by tuananh** [ShogunPanda/cronometro#2]
```
const results = cronometro({
        ['my async function']: function () {
            myAsyncFunction()
        },
        ['syncFunction']: function () {
            mySyncFunction()
        },
    })
```

-  without `await` in the async function, the ops per second is very high. It's like it's just firing promises without counting number of promises resolved.
- with `await`, the number is much lower.

- however, if i do sth like push 10k promises to an array and do `Promise.all()`, the number is much higher than 1 but lower than 2.

what's the proper way to benchmark async function here?

**Comment by ShogunPanda** [comment]
Hi!
I think I should probably make it clearer in the docs.

Without await you're right, cronometro will allocate those promises but won't wait for their completion.

What I forgot to mention in the docs is that for promise (or async function) you should return them in the function. Cronometro will then wait for completion.

So, your example becomes:

```javascript
const results = cronometro({
        ['my async function']: function () {
            return myAsyncFunction()
        },
        ['syncFunction']: function () {
            mySyncFunction()
        },
    })
``` 

Let me know if it works, otherwise we have a bug :)

**Comment by tuananh** [comment]
@ShogunPanda 

is there anyway we can let cronometro fire more than 1 promise at once?

eg:

when i test with the below, i got ~ 300 ops/sec

```
const results = cronometro({
        ['my async function']: function () {
            return myAsyncFunction()
        },
        ['syncFunction']: function () {
            mySyncFunction()
        },
    })
```

but when i try to push 10k promises to an array and `await Promise.all()`, it will finish it < 8 seconds.

**Comment by ShogunPanda** [comment]
Well, inside the function you can do whatever you want ;)
Cronometro itself does not impose a limit on the number of spawn promises inside a single iteration. It just waits for the returned promise to be resolved, trying to add the least overhead possible. It is up to you to make sure that the two tests perform similar operations so that results are comparable.
So doing something like this is perfectly fine:

```
const results = cronometro({
        ['my async function']: function () {
            return Promise.all([myAsyncFunction(), myAsyncFunction(), myAsyncFunction()]
        },
        ['syncFunction']: function () {
            mySyncFunction()
        },
    })
```

But, probably then a more honest test would be:

```
```
const results = cronometro({
        ['my async function']: function () {
            return Promise.all([myAsyncFunction(), myAsyncFunction(), myAsyncFunction()])
        },
        ['syncFunction']: function () {
            mySyncFunction()
            mySyncFunction()
            mySyncFunction()
        },
    })
```

Anyway promises (or async function) will always be slower than sync function (even if they don't do any async operation inside) since they have additional scheduling overhead.

If you can (or wish) upload your functions (or a slimmed version) I can maybe give you more hints.
