### ISSUE TITLE
Comparing a package with a built-in package is not possible

### ISSUE THREAD

**Issue by anonrig** [ShogunPanda/cronometro#3]
Since native packages have their own path and with Node 18, there are newly supported Node snapshots, currently, requiring/importing a package is not comparable with a native one, which causes wrong benchmarking results on complex benchmarks.

Importing benchmark example: https://github.com/anonrig/fast-querystring/pull/24

Wrong benchmark example: https://github.com/nodejs/undici/pull/1679

There needs to be a way of comparing a package with a native package, and not caring about the `require` times of both packages.

**Comment by ShogunPanda** [comment]
I don't really see the issue here.

There is a difference in benchmarking a package importing and its operation. Especially since import/require is only done once so there little benefit in benchmarking this.

In other words, doing the following:

```
import benchmark from "cronometro";

await benchmark(
  {
    async native() {
      const n = await import("node:fs/promise");
      return n.writeFileSync(/* ... */);
    },
    async custom() {
      const c = await import("custom-fs");
      return c.writeFileSync(/* ... */);
    },
  },
  { warmup: true },
);
```

is wrong as the import are accounted in the bench but in the real word this would never happen.

The following is IMHO the correct way to benchmark.

```
import benchmark from "cronometro";
import n from "node:fs/promise";
import c from "custom-fs";

await benchmark(
  {
    async native() {
      return n.writeFileSync(/* ... */);
    },
    async custom() {
      return c.writeFileSync(/* ... */);
    },
  },
  { warmup: true },
);
```

Note that cronometro does not start measuring time when the benchmark file is executed but only the execution time of the benchmark functions.

Closing this as I don't see as an issue.
